### ISSUE TITLE
Time Out doesn't save password

### ISSUE THREAD

**Issue by reneelynn** [devgeeks/Encryptr#112]
I finally got it to break once! If you are using it to set up a password for you, and then walk away without saving it and are gone too long, when you come back and try to save it times out and you lose the password you set. 

I need to do some more investigation on how long it takes to time out.

**Comment by helveticade** [comment]
This needs to be tested for 1.2.0 before we can close it.

**Comment by modedeep** [comment]
Option to choice timeout duration?
