### ISSUE TITLE
Multiple incorrect credential error messages

### ISSUE THREAD

**Issue by MichaelJAllen** [devgeeks/Encryptr#126]
I'm using v1.0.1 and I've noticed that I get three different errors if I enter incorrect passwords...

The first is `Authentication error: Could not parse secret key` and the second is `Authentication error: Incorrect password`. In both cases, I used a valid username. It could just be coincidence, but I seem to always get the first error message with one particular set of wrong passwords and the other message with a completely different set.

Out of curiosity, when I entered what I hoped would be an invalid user account name, I received a third error message: `Authentication error: Account not found.`

This doesn't seem right. I would prefer that there be a single "authentication error" message, regardless of the account or password used; having different errors potentially leaks some information to a hacker - not least of which is whether they have a valid account name (although that can be determined by trying to create an account).

As a side issue, there also do not appear to be any consequences for entering a number of invalid password entries, such as locking out requests from the originating IP address for a period of time after three failed login attempts.

**Comment by participante0** [comment]
I'm not sure if I should write here or in the Crypton issue #320.

There is another error message. When I try to login with an existing account but an incorrect password, very few times I see this message:
`Authentication error: Client key length is less than 256 bits.`
What does it mean?
I wrote more than 12 characters in the password field but less than the amount of characters of the correct password.

**Comment by daviddahl** [comment]
this is definitely a crypton error. It is hard to reproduce but is related to SRP.

**Comment by taecilla** [comment]
BTW, what does `Could not parse secret key` means? I cannot log in.

**Comment by devgeeks** [comment]
:/

This is a weird error I have seen a couple times... usually when I do something like leave off 1 character from my passphrase.

@daviddahl do you know why this might happen? Is it leaking anything?

**Comment by taecilla** [comment]
I just realized that I was typing a wrong password, but almost identical to the correct one (I write by hand certain numbers too similar to letters). It feels really weird and wrong :S

**Comment by devgeeks** [comment]
I think for my part I should just homogenise the error messages.

**Comment by MichaelJAllen** [comment]
Thanks for addressing the original issue about the various different error messages! (Sorry it's taken me so long to acknowledge, as I wasn't receiving updates for some reason.)

It looks like the second point I raised about there being no penalties for a number of incorrect login attempts is now being tracked by issue #212, for anyone interested in that.
