### ISSUE TITLE
Error copying to the clipboard some passwords

### ISSUE THREAD

**Issue by participante0** [devgeeks/Encryptr#137]
You can reproduce the issue (at least) in Windows and Linux.
The password is stored correctly but when you copy it to the clipboard is different.

Example 1:
Saved: `m]$L{ym<!o6sWQwb=bPX{I>Q-M4gx(Yiu;`
Copied: `m]$L{ymQ-M4gx(Yiu;`

Example 2:
Saved: `BRlCEtH<voux;!Y7>CJN{P=.`
Copied: `BRlCEtHCJN{P=.`

Problem: `< >`

These symbols are perfectly valid in several places to write passwords. I would like to know the cause of the problem and hopefully be corrected in the next version. I love Encryptr.
Sorry for my english. I speak spanish.

**Comment by participante0** [comment]
Another error related...
As I write this password: `123"abc`, saved well, looks good, I can copy it to the clipboard well. But when I want to edit, it looks like this:.`123`. Another problematic symbol: `"`.

**Comment by devgeeks** [comment]
Thanks.

**Comment by ganon11000** [comment]
I was about to post this as an issue but I see it's been fixed for next release?

**Comment by helveticade** [comment]
This is fixed for next release @ganon11000 @participante0
