### ISSUE TITLE
Code audit using Coverity

### ISSUE THREAD

**Issue by landroni** [devgeeks/Encryptr#143]
Have you considered auditing your code using the automated scan utility Coverity? 
https://scan.coverity.com/

Their tool is being used by heavy-hitters like LibreOffice, Linux Kernel, Firefox or Python. It may be worth submitting encryptr to Coverity, too, to watch out for pesky implementation omissions.

**Comment by helveticade** [comment]
Thanks @landroni. We're looking into it.
