### ISSUE TITLE
[Debian] "`GLIBC_2.14 [or 2.15]' not found"

### ISSUE THREAD

**Issue by mwehu** [devgeeks/Encryptr#147]
>Release: 7.8 (wheezy) 64-bit
>Installer: encryptr_1.1.0-1_amd64.deb

The following error occurs when I try to start the program:

>user@debian:~$ Encryptr 
>/usr/bin/Encryptr: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.14' not found (required by /usr/bin/Encryptr)
>/usr/bin/Encryptr: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.15' not found (required by /usr/bin/Encryptr)

**Comment by mwehu** [comment]
>user@debian:~$ /lib/x86_64-linux-gnu/libc.so.6
>GNU C Library (Debian EGLIBC 2.13-38+deb7u7) stable release version 2.13, by Roland McGrath et al.
>Copyright (C) 2011 Free Software Foundation, Inc.
>This is free software; see the source for copying conditions.
>There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
>PARTICULAR PURPOSE.
>Compiled by GNU CC version 4.4.7.
>Compiled on a Linux 3.2.65 system on 2015-01-26.
>Available extensions:
>	crypt add-on version 2.1 by Michael Glad and others
>	GNU Libidn by Simon Josefsson
>	Native POSIX Threads Library by Ulrich Drepper et al
>	BIND-8.2.3-T5B
>libc ABIs: UNIQUE IFUNC
>For bug reporting instructions, please see:
><http://www.debian.org/Bugs/>.

The installed version of Glib is lower, why the installer does not accuse any errors during installation?

**Comment by devgeeks** [comment]
That is odd. I wonder if the .deb is supposed to have detected that?
