### ISSUE TITLE
./encryptr-bin: error while loading shared libraries: libudev.so.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by gavinengel** [devgeeks/Encryptr#149]
I'm getting this error after downloading this from my Fedora 21:
https://github.com/devgeeks/Encryptr/releases/download/v1.1.0/encryptr_1.1.0-1_amd64.tar.gz

Here is the error:

   ./encryptr-bin: error while loading shared libraries: libudev.so.0: cannot open shared object file: No such file or directory

If it helps any, here is a bit about my system:

```
gavin@localhost:~/Desktop/Encryptr$ locate libudev
/opt/google/chrome/libudev.so.0
/opt/vivaldi/libudev.so.0
/usr/lib/libudev.so.1
/usr/lib/libudev.so.1.6.1
/usr/lib64/libudev.so.1
/usr/lib64/libudev.so.1.6.1
/usr/lib64/vlc/plugins/services_discovery/libudev_plugin.so
gavin@localhost:~/Desktop/Encryptr$ uname -a
Linux localhost.localdomain 3.18.5-201.fc21.x86_64 #1 SMP Mon Feb 2 21:00:58 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

Should I create a symlink to libudev.so.0 from libudev.so.1?

**Comment by devgeeks** [comment]
You shouldn't have to run `encryptr-bin` directly. There should be a shell script wrapper `encryptr` that handles symlinking `libudev.so.1` and setting the `LD_LIBRARY_PATH`

**Comment by devgeeks** [comment]
I think I really need a README or INSTALL or whatever in the Linux 'other' version

**Comment by gavinengel** [comment]
Thanks, and sorry for the trouble!

**Comment by devgeeks** [comment]
No, thanks for letting me know. I really do need documentation for this stuff, especially when there is no "installer"
