### ISSUE TITLE
Entry "types" need to be abstracted to JSON structures

### ISSUE THREAD

**Issue by devgeeks** [devgeeks/Encryptr#15]
Instead of an entry "type" being described as an object with a constructor like this:

[https://github.com/devgeeks/Encryptr/blob/master/src/models/types/PaswordTypeModel.js](https://github.com/devgeeks/Encryptr/blob/master/src/models/types/PaswordTypeModel.js)

It would be much better if it could be described simply as a JSON structure.

I tried this early on, but had issues with the prototype chain being clobbered when not using "new". 

Possibly all this needs is to be described as **actual** JSON instead of a JSON-like JS object.

ie: `'{"foo":"bar"}'` as opposed to `{foo:"bar"}`.. and be instantiated using `JSON.stringify()`

**Comment by helveticade** [comment]
3.0 will fix this.
