### ISSUE TITLE
iOS Splash screen seem to be "squashed" on 6 plus

### ISSUE THREAD

**Issue by devgeeks** [devgeeks/Encryptr#155]
Just as the app is launching.

Maybe the splash utility isn't getting the sizes quite right?

**Comment by devgeeks** [comment]
This seems to be happening when I launch the app while I am tethering.

**Comment by lorensr** [comment]
This happens to me on an unrelated app, only when tethered.

**Comment by devgeeks** [comment]
@lorensr :/

I wonder if there is any way around it short of the new .xib splashscreens?

**Comment by lorensr** [comment]
Don't know, I'm just happy that it only occurs in such a rare circumstance.

**Comment by helveticade** [comment]
This is a cordova problem. We'll raise it with them.
