### ISSUE TITLE
Add server software for self-hosting.

### ISSUE THREAD

**Issue by Vaaaaar** [devgeeks/Encryptr#156]
>You don't even need to hand over any personal data to register.
>Not your name, and not your email address. The app only requires a username and a passphrase.

What happen if someone use your username and passphrase?

That's one of the reason I don't trust cloud.

Please add "server" software for self-hosting.
I prefer host it on my server by myself.

**Comment by devgeeks** [comment]
The server software is Crypton: https://crypton.io

It's already possible to self-host.

Change this line: https://github.com/devgeeks/Encryptr/blob/master/src/app.js#L33 to point to your Crypton server.

**Comment by lgommans** [comment]
Is this still true, can this be hosted with github.com/devgeeks/crypton (which hasn't been updated since 2014)?

**Comment by devgeeks** [comment]
The correct location for Crypton is https://github.com/SpiderOak/crypton which has. Wen updated more recently. 

It's still currently possible to host your own Crypton server, though you'd also need to compile client apps as well as the server address is hard coded in the apps.

**Comment by lgommans** [comment]
A configuration field would be nicer, but I kind of expected recompilation would be needed. Thanks for the reply!

**Comment by paulequilibrio** [comment]
Is this still true? Where is Crypton now?
