### ISSUE TITLE
Hashicorp Vault Integration

### ISSUE THREAD

**Issue by certifiedloud** [devgeeks/Encryptr#157]
It would be nice to have the option of using my own server with the Encryptr client. More specifically, it would be nice to use [Vault](https://github.com/hashicorp/vault) as the backend. 

It's a big change for sure, but hopefully not wishful thinking.

**Comment by helveticade** [comment]
@certifiedloud – thanks for the suggestion. You can self host Encryptr with Crypton, but at this stage we won't be supporting other backends.
