### ISSUE TITLE
Can we have full text search on names field and also tagging

### ISSUE THREAD

**Issue by holajoyce** [devgeeks/Encryptr#158]
Hi Devgeeks developers,

For ease of use, can we have an index on the names field, and also ability to tag them?

Thanks

**Comment by devgeeks** [comment]
Due to the zero-knowledge aspects of Crypton, a full search might not be possible, however, I am planning on allowing searching/filtering on the main "index" view (the initial list of entries).

See: #46 

I am also working on a way to use tags to organise the list better.

See: #109
