### ISSUE TITLE
Uncaught node.js Error

### ISSUE THREAD

**Issue by 0x24D** [devgeeks/Encryptr#164]
I was rapidly creating and discarding password entries (needed a password without symbols) and I received this error.

`Uncaught node.js Error`
 `TypeError: undefined is not a function`
   ` at Backbone.View.extend.a_clickHandler (file:///C:/Users/*User*/AppData/Local/Temp/nw1716_22568/js/Encryptr.js:727:11)`
    `at HTMLDivElement.delegator (file:///C:/Users/*User/AppData/Local/Temp/nw1716_22568/components/zepto/zepto.js:1824:43)`
   `at HTMLDivElement.handler.proxy (file:///C:/Users/*User*/AppData/Local/Temp/nw1716_22568/components/zepto/zepto.js:1699:31)`

**Comment by helveticade** [comment]
Hey @xDanneee, we'll take a look into it and get back to you.

**Comment by f3rno** [comment]
Ditto, I also observed this. Created a few passwords in rapid succession before.

**Comment by devgeeks** [comment]
I think I have this cleared up. Should be fixed in 2.0.0
