### ISSUE TITLE
Changes that should be made to the Encryptr bash script (would make a pull request but I can't find it in this repository)

### ISSUE THREAD

**Issue by crossroads1112** [devgeeks/Encryptr#168]
[Here](http://0bin.net/paste/gISvWpW46tvrF+VN#RgHhAumUOsLe4u4seLGCfFhlFhVvzcOU9e0hqu6Hodt) is the diff (every line shows a difference because there were a bunch of useless spaces at the end of every line that I removed.)

**Comment by crossroads1112** [comment]
My patch is wrong. Will resubmit when fixed

**Comment by devgeeks** [comment]
Well, that shell script really *should* be in the repo. I'll add it today, then you can do a proper PR against it.

I'll also remove any trivial whitespace.

The script is based on "Creating a symlink for your package in the postinstall script" here: https://github.com/nwjs/nw.js/wiki/The-solution-of-lacking-libudev.so.0

**Comment by devgeeks** [comment]
https://github.com/devgeeks/Encryptr/blob/master/resources/Encryptr-linux.sh
