### ISSUE TITLE
Host data on different cloud storage provider(s).

### ISSUE THREAD

**Issue by chrisidefix** [devgeeks/Encryptr#172]
I am not 100% sure if this is already possible, but similar to issue #156, it would be great to be able to store the data not just locally, but also at any cloud provider I choose.

Dropbox or iCloud Drive or any similar service may come to mind. Would it make sense to be able to sync the data through such a third-party service, which could also somewhat address/improve the offline availability (#122)?

Ideally, every Encryptr installation (on different machines) could be configured to display the data currently present in this synced folder. When I am offline, I can still read / add new items, which will be synced later on (this could obviously also lead to conflicts, though).

**Comment by helveticade** [comment]
Encryptr uses [Crypton](https://crypton.io) to provide zero-knowledge encryption. Due to the nature of how Crypton works, its not really possible to offer other syncing options. You can, however, clone Crypton and self-host. See #156 for more info.

**Comment by elya5** [comment]
How about having an option in the GUI to set your own server address? Then it would not be necessary for users to change that line again after every update.

**Comment by devgeeks** [comment]
:+1:
