### ISSUE TITLE
Request:Database Import and 2 Factor Auth

### ISSUE THREAD

**Issue by tuphamnguyen** [devgeeks/Encryptr#186]
I'm thinking of switching to Encryptr but I really do not want to manually enter my hundreds of passwords. It would be great if I could import a LastPass XML file or KeePass Database file.

Also for an extra layer of security, it would be great if there is a 2 factor option be it hardware or software.

**Comment by devgeeks** [comment]
CSV import / export is certainly coming. It is VERY high on my TODO list.

I am also looking into 2fa options.

I will close this issue, but only because both of these features are being tracked in other issues.

import / export: #104 and #159 

2fa: #123
