### ISSUE TITLE
Editing an entry before it has finished loading generates error. 

### ISSUE THREAD

**Issue by reneelynn** [devgeeks/Encryptr#187]
1) Log in to Encryptr
2) Select an Entry
3) Before it finishes loading select "edit"
4) Error.

Consistently reproducible. 
![screen shot 2015-08-30 at 11 15 56 pm](https://cloud.githubusercontent.com/assets/3867179/9581463/3d4a7048-4fc5-11e5-9f8a-8c36917ab72a.png)

**Comment by 13o6** [comment]
can confirm, following the same steps: 
![exception](https://cloud.githubusercontent.com/assets/10118516/9582485/e5014042-5005-11e5-8f8b-99fc1f8932da.jpg)

**Comment by devgeeks** [comment]
:+1:

**Comment by helveticade** [comment]
Do we want to add this to a milestone?

**Comment by devgeeks** [comment]
Added to 2.0.0

**Comment by agentofcode** [comment]
This also happens if you delete an entry on one device and try to access it on a different one.

**Comment by devgeeks** [comment]
I am pretty sure I have this fixed in the upcoming 2.0.0 release.
