### ISSUE TITLE
Uncaught node.js error when clicking on add password..

### ISSUE THREAD

**Issue by xrisk** [devgeeks/Encryptr#217]
![Screenshot](https://i.imgur.com/BaYulqs.png)

**Comment by devgeeks** [comment]
Yeah, this is a known issue and should be fixed in the version being released in the next couple of weeks :/

**Comment by xrisk** [comment]
Oh alright then. btw are there any plans for offline caching of passwords?

**Comment by devgeeks** [comment]
Plans, absolutely. Not sure where on the roadmap it is at this stage though.
