### ISSUE TITLE
iOS Perf issues

### ISSUE THREAD

**Issue by daviddahl** [devgeeks/Encryptr#57]
Performance lacks and whatnot on iOS!

**Comment by devgeeks** [comment]
Getting VERY close now.

:)

**Comment by daviddahl** [comment]
:) !!!

**Comment by abgoldstein** [comment]
That's great! Anything I can do to help out?

**Comment by devgeeks** [comment]
@abgoldstein - Don't think so. At this stage, I think iOS is basically working. It just needs heavy testing.

However, it will mean an update to the backend and we have some other ops related changes that will have to be done first.

I am hoping to get it released as soon as I can, but between the backend update, testing and getting a crypto app past Apple (heh), I think it may be a few weeks off still...

**Comment by helveticade** [comment]
D O N E
